version: '3'

services:
  # Layanan Backend Flask
  backend:
    build:
      context: ./backend  # Path ke direktori backend Anda
    container_name: flask-backend
    ports:
      - "5000:5000"  # Port backend
    environment:
      - MQTT_BROKER=${MQTT_BROKER}  
      - MQTT_PORT=${MQTT_PORT}      
      - MQTT_USER=${MQTT_USER}      
      - MQTT_PASS=${MQTT_PASS}      
      - MQTT_IMAGE_TOPIC=${MQTT_IMAGE_TOPIC}
      - MQTT_LATENCY_TOPIC=${MQTT_LATENCY_TOPIC}  
      - MYSQL_HOST=${MYSQL_HOST}    
      - MYSQL_PORT=${MYSQL_PORT}    
      - MYSQL_USER=${MYSQL_USER}    
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}  
      - MYSQL_DB=${MYSQL_DB}        
      - AES_KEY=${AES_KEY}  
      - URL_FRONTEND=${URL_FRONTEND}        
    networks:
      - app-network
    restart: always

  # Layanan Frontend React
  frontend:
    build:
      context: ./frontend  # Path ke direktori frontend Anda
    container_name: react-frontend
    ports:
      - "3000:3000"  # Port frontend
    depends_on:
      - backend  
    environment:
      - REACT_APP_BACKEND_URL=${URL_BACKEND}  
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
